set MATLAB=C:\PROGRA~1\MATLAB\R2015b
"%MINGW_DIR%\bin\sh.exe" --login -c "cd \"%CD%\" && make -f setpoints_model.mk  MAT_FILE=0 DEBUG=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DON_TARGET_WAIT_FOR_START=0""
